# Railway Configuration for Frontend Service

[build]
builder = "nixpacks"

[deploy]
# Health check endpoint
healthcheckPath = "/"

# Restart policy
restartPolicyType = "on_failure"

# Start command
startCommand = "npm run start"

