-- ReportType enum'una tüm değerleri ekle
ALTER TYPE "ReportType" ADD VALUE IF NOT EXISTS 'FULL_REPORT';
ALTER TYPE "ReportType" ADD VALUE IF NOT EXISTS 'ENGINE_SOUND_ANALYSIS';
ALTER TYPE "ReportType" ADD VALUE IF NOT EXISTS 'COMPREHENSIVE_EXPERTISE';
ALTER TYPE "ReportType" ADD VALUE IF NOT EXISTS 'DAMAGE_ASSESSMENT';
ALTER TYPE "ReportType" ADD VALUE IF NOT EXISTS 'DAMAGE_ANALYSIS';
ALTER TYPE "ReportType" ADD VALUE IF NOT EXISTS 'PAINT_ANALYSIS';
ALTER TYPE "ReportType" ADD VALUE IF NOT EXISTS 'VALUE_ESTIMATION';

-- ServiceType enum'una tüm değerleri ekle (eğer yoksa)
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'ENGINE_SOUND_ANALYSIS';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'COMPREHENSIVE_EXPERTISE';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'DAMAGE_ANALYSIS';

-- Kontrol et
SELECT 'ReportType Enum:' as info;
SELECT unnest(enum_range(NULL::"ReportType")) AS value ORDER BY value;

SELECT 'ServiceType Enum:' as info;
SELECT unnest(enum_range(NULL::"ServiceType")) AS value ORDER BY value;

