# Nixpacks Configuration for Railway
# Bu dosya Railway'nin build sürecini optimize eder

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd frontend && npm run build"
]

[phases.start]
cmd = "npm run start"

# Environment variables
[variables]
NODE_ENV = "production"

# Port configuration
[providers.railway]
port = "$PORT"
